### PR TITLE
Albina khamitova/issue19

### PR DESCRIPTION
**Pull request by Albina757**

### CODE REVIEW

**Review by SuesmairT — APPROVED** [review]
Super

**Review by IrynaKosiak7 — APPROVED** [review]
good work

**Review by FartushkoY — APPROVED** [review]

**Review by Julia1387 — APPROVED** [review]

**Review by GroismanV — APPROVED** [review]

**Review by corinapavliuc — APPROVED** [review]

**Review by AnnaDubinets — APPROVED** [review]

**Review by SmolnikNata — APPROVED** [review]

**Review by GroismanV — APPROVED** [review]

**Comment by Boxer2023** [comment]
great job

**Comment by GroismanV** [comment]
++

**Pull request merged**
